config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  root 'plans#index'
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  resources :plans, only: [:index, :show, :create, :update, :destroy, :new ]
end

app/models/plan.rb
# create_table "plans", force: true do |t|
#   t.datetime "start_time",         null: false
#   t.datetime "end_time",           null: false
#   t.integer  "booker_id"
#   t.integer  "message_pattern_id"
#   t.boolean  "active"
#   t.datetime "created_at"
#   t.datetime "updated_at"
# end

class Plan < ActiveRecord::Base
  validates :start_time, :end_time, :message_pattern_id, :active, :booker_id, :number_of_fake_women, presence: true
  
  belongs_to(
    :booker,
    class_name: "User",
    foreign_key: :booker_id,
    primary_key: :id
  )
  
  # has_many(
  #   :scheduled_messages,
  #   class_name: "ScheduledMessage",
  #   foreign_key: :plan_id,
  #   primary_key: :id
  # ), dependent: :destroy
  
  has_many :scheduled_messages, dependent: :destroy
  has_many :delayed_jobs, dependent: :destroy
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all.where(booker_id: current_user.id)
  end
  
  def show
    @plan = Plan.find(params[:id])
    @scheduled_messages = ScheduledMessage.where(plan_id: params[:id])
    render :show
  end
  
  def create
    @plan = Plan.create(
      booker_id: current_user.id,
      start_time: Time.parse(plan_params[:start_time]),
      end_time: Time.parse(plan_params[:end_time]),
      message_pattern_id: plan_params[:message_pattern_id].to_i,
      number_of_fake_women: plan_params[:number_of_fake_women].to_i,
      active: true
    )
    
    # @plan = Plan.create(plan_params)
    
    if @plan.save!
      #create the associated Scheduled messages
      #right now only create one message per woman
      originating_phone_numbers = ["585-563-5535", "585-563-5535"]

      #TODO change this when you deploy the application because this is on github right now      
      account_sid = ENV['TWILIO_APP_ID']
      auth_token = ENV['TWILIO_SECRET']
    
      # set up a client to talk to the Twilio REST API
      @client = Twilio::REST::Client.new account_sid, auth_token
      
      plan_params[:number_of_fake_women].to_i.times do |i|
        @scheduled_message = ScheduledMessage.create(
          plan_id: @plan.id,
          send_at: (Time.at((plan_params[:end_time].to_f - plan_params[:start_time].to_f)*rand + plan_params[:start_time].to_f)), 
          body: Faker::Company.bs,
          from_phone_number: originating_phone_numbers[i], 
          active: true
        )
        if @scheduled_message.save!
          @scheduled_message.delay(:run_at => 10.seconds.from_now).send_via_twilio(@client)
        end
      end
      
      redirect_to plan_url(@plan)
    else
      
    end

  end
  
  def update
    
  end
  
  def destroy
    @plan = Plan.find_by(id: params[:id])
    puts @plan.id
    
    if @plan.booker_id == current_user.id 
      @plan.delete
      redirect_to plans_url
    else
      #they are trying to delete a plan they do not own.  scold them for being a hacker.
    end
  end
  
  def new
    
  end
  
  private
  def plan_params
    params.require(:plan).permit(:booker_id, :start_time, :end_time, :message_pattern_id, :number_of_fake_women, :id)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.html.erb
<!--validates :start_time, :end_time, :message_pattern_id, :active, :booker_id, :number_of_fake_women -->

<ul>
	<% @plans.each do |plan| %>
		<%#= link_to plan_url(plan) %>
		<li><a href=<%="/plans/" + plan.id.to_s %>>Go to plan</a> Plan ID: <%= plan.id %>, Plan Start Time: <%= plan.start_time %>, Plan End Time: <%= plan.end_time %>, booker: <%= plan.booker.email %>, Number of fake women: <%= plan.number_of_fake_women %><%= button_to('Delete this plan', plan_url(plan),
          method: "delete", remote: true, data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %></li>
	<% end %>
</ul>

<%= link_to "Create New Plan", new_plan_url %>

app/views/plans/new.html.erb
<!-- Plan.create(start_time: (Time.now), end_time: (Time.now + 360), booker_id: 1, message_pattern_id: 1, number_of_fake_women: 3, active: true) -->

<form action="/plans" method="POST">

  <input
    type="hidden"
    name="authenticity_token"
	value="<%= form_authenticity_token %>">

  <label>Start Time:
  <input type="datetime" name="plan[start_time]" value="2015-01-25 05:16:42">
  </label>
  <br>
  
  <label>End Time:
  <input type="datetime" name="plan[end_time]" value="2015-01-25 06:16:42">
  </label>
  <br>
  
  <label>Message Pattern ID:
  <input type="text" name="plan[message_pattern_id]" value="1">
  </label>
  <br>

  <label>Number of Fake Women:
  <input type="text" name="plan[number_of_fake_women]" value="2">
  </label>
  <br>
  
  <input type="submit">
</form>

app/views/plans/show.html.erb
<!-- ScheduledMessage.create(plan_id: 1, send_at: (Time.now + 60), body: "Hi Joe!", from_phone_number: "585-563-5535", active: true) -->

<ul>
	<% @scheduled_messages.each do |message| %>
		<li>Message ID: <%= message.id %>, Message Scheduled to send: <%= message.send_at %>, Message body: <%= message.body %>, Message will be sent from: <%= message.from_phone_number %>, Is message active?: <%= message.active %></li>
	<% end %>
</ul>

<%= link_to "back to all plans", plans_url %>